# Common
## Imports

In [2]:
from platform import python_version

print(python_version())

3.7.6


In [21]:
import gym

import hiive.mdptoolbox as mdptoolbox
from hiive.mdptoolbox.mdp import ValueIteration, PolicyIteration, QLearning

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from time import time

%matplotlib inline

ValueIteration?

## Example Code

In [6]:
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

[-0.03977883 -0.0425485   0.01526147  0.0352031 ]
[-0.0406298   0.15235131  0.01596553 -0.25262587]
[-0.03758278  0.34724169  0.01091302 -0.54023051]
[-3.06379433e-02  1.51968054e-01  1.08407199e-04 -2.44129133e-01]
[-0.02759858 -0.04315545 -0.00477418  0.04858799]
[-0.02846169 -0.23820862 -0.00380242  0.3397608 ]
[-0.03322586 -0.04303277  0.0029928   0.04588124]
[-0.03408652  0.15204614  0.00391043 -0.24585593]
[-0.0310456  -0.04313144 -0.00100669  0.04805787]
[-3.19082248e-02  1.52004931e-01 -4.55361515e-05 -2.44942510e-01]
[-0.02886813 -0.04311637 -0.00494439  0.04772605]
[-0.02973045 -0.23816707 -0.00398987  0.33884489]
[-0.0344938  -0.04298858  0.00278703  0.04490646]
[-0.03535357  0.1520933   0.00368516 -0.24689583]
[-0.0323117   0.34716242 -0.00125275 -0.5384141 ]
[-0.02536845  0.15205811 -0.01202104 -0.24612616]
[-0.02232729 -0.04289011 -0.01694356  0.04274093]
[-0.02318509 -0.23776505 -0.01608874  0.33003022]
[-0.02794039 -0.04241781 -0.00948814  0.0323174 ]
[-0.02878875 -0.23

[ 0.01329695  0.36829152  0.00314285 -0.51017429]
[ 0.02066278  0.56336906 -0.00706064 -0.80186515]
[ 0.03193016  0.75858712 -0.02309794 -1.09676076]
[ 0.0471019   0.95400548 -0.04503315 -1.3966003 ]
[ 0.06618201  1.14965773 -0.07296516 -1.7030164 ]
[ 0.08917517  1.34553995 -0.10702549 -2.01749067]
[ 0.11608597  1.54159723 -0.1473753  -2.34129935]
[ 0.14691791  1.3480784  -0.19420129 -2.09733941]
Episode finished after 40 timesteps
[-0.02916503  0.02898058  0.0235696   0.00409386]
[-0.02858542  0.22375672  0.02365147 -0.28106038]
[-0.02411028  0.41853346  0.01803027 -0.56619088]
[-0.01573961  0.61339789  0.00670645 -0.8531394 ]
[-0.00347165  0.41818516 -0.01035634 -0.55835522]
[ 0.00489205  0.22321011 -0.02152344 -0.26895303]
[ 0.00935625  0.02840182 -0.0269025   0.01686431]
[ 0.00992429 -0.16632419 -0.02656522  0.30093926]
[ 6.59780421e-03  2.91661238e-02 -2.05464332e-02 -2.00910326e-06]
[ 0.00718113 -0.16565523 -0.02054647  0.28612811]
[ 0.00386802  0.02975363 -0.01482391 -0.01296355

[-0.03203865  0.03282688 -0.06611073 -0.14605109]
[-0.03138211 -0.16128909 -0.06903175  0.1250644 ]
[-0.03460789  0.03475044 -0.06653046 -0.18857374]
[-0.03391288  0.23075802 -0.07030193 -0.50148019]
[-0.02929772  0.42679688 -0.08033154 -0.81546385]
[-0.02076178  0.23286136 -0.09664081 -0.54909077]
[-0.01610456  0.42919853 -0.10762263 -0.87059054]
[-0.00752059  0.62560682 -0.12503444 -1.19507842]
[ 0.00499155  0.82210594 -0.14893601 -1.52419053]
[ 0.02143367  1.01867939 -0.17941982 -1.85941194]
Episode finished after 18 timesteps
[ 0.02832467 -0.02400418 -0.03705378 -0.02346675]
[ 0.02784459  0.17162903 -0.03752312 -0.32760645]
[ 0.03127717  0.36726454 -0.04407525 -0.63188236]
[ 0.03862246  0.56297281 -0.05671289 -0.9381136 ]
[ 0.04988192  0.36865947 -0.07547517 -0.66377686]
[ 0.05725511  0.17466414 -0.0887507  -0.39578092]
[ 0.06074839  0.37092587 -0.09666632 -0.71507333]
[ 0.06816691  0.17726548 -0.11096779 -0.45431458]
[ 0.07171222 -0.01612682 -0.12005408 -0.19856796]
[ 0.07138968  

In [30]:
# save state
import dill

dill.dump_session("notebook_env.db")


AttributeError: 'NoneType' object has no attribute 'startswith'